db:
  active: True
  name: "eth_o2_s3"
  ip: "localhost"
  port: "27017"

method:
  method_family: "gfn2"
  method: "gfn2"
  basis_set: ""
  program: "xtb"
  vfilter: {"C": 4, "H": 16}

files:
  pathfinder:
    path: "./vizchemoton/resources/crn_pathfinder.json"
    mode: "write"
  reactions:
    path: "./vizchemoton/resources/reactions.csv"
    mode: "write"
  compounds:
    path: "./vizchemoton/resources/compounds.json"
    mode: "write"

output:
  file: "network.html"
  title: "Chemoton graph"
  smiles: True
  verbose: True

graph:
  dist_adduct: 3.0
  size: [1400, 800]
  layout: "kamada_kawai"
  map_field: "degree"



