scine:
  active: True
  name: "ozone_tme_lcpbe"
  ip: "localhost"
  port: "27017"
  verbose: True
  method:
    method_family: "dft"
    method: "lc-pbe"
    basis_set: "def2-svp"
    program: "orca"
  pathfinder:
    mode_graph: "write"
    path_graph: "./vizchemoton/resources/pathfinder_graph_tme_dft.json"
    mode_costs: "write"
    path_costs: "./vizchemoton/resources/pathfinder_costs_tme_dft.json"
    init_costs: {"660d49de86b7e52a0c3bc06c": 100, # ozone
                 "660d4a1086b7e52a0c3bc070": 1,   # tme
                 "6649c98d86b7e5495e6e44ac": 100} # water   

cheminfo:
  verbose: False
  rdkit:
      active: False
      method: "hybrid"
      props: ["MolLogP", "CalcTPSA", "MolWt"]
  database:
      pubchem: False
      chembl: False
      chebi: False

files:
  mode_reactions: "write"
  path_reactions: "./vizchemoton/resources/reactions_tme_dft.csv"
  mode_compounds: "write"
  path_compounds: "./vizchemoton/resources/compounds_tme_dft.json"
  path_graphml: "./vizchemoton/resources/network_tme_dft.graphml"

html:
  pathsearch:
    use_costs: True 
    Npaths: 5
    max_length: 6
    source: "c1" 
    target: "c48"
  dist_adduct: 3.0
  layout: "kamada_kawai" 
  map_field: "pfcost"
  title: "Ozonation of Tetramethylethene with Chemoton"
  path_network: "./vizchemoton/resources/network_tme_dft.html"


   



