"""
Enric Petrus, December 2024. Added SCINE helper function to link with the
amk-tools generation of HTML files.
Diego Garay-Ruiz, November 2023. Collection of helper functions to link
amk-tools and grrm-tools, generating interactive
HTML dashboards to visualize GRRM-generated reaction networks.
"""

# Standard Library Imports
from collections import Counter
import copy

# Third-Party Library Imports
import numpy as np
import bokeh.plotting
import bokeh.models as bkm
import RXVisualizer as arxviz
import networkx as nx
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score


def cluster_nodes(descriptors, n_clusters="silhouettes", verbose=True):
    node_ids = list(descriptors.keys())
    X = np.array([descriptors[n] for n in node_ids])

    if n_clusters == "silhouettes":
        silhouettes = []
        k_values = range(2, int(np.sqrt(len(X) / 2)))  # candidate k values
        tolerance = 0.005
        window = 5
        for k in k_values:
            print(type(X))
            print(len(X))
            print(type(X[0]))
            print(len(X[0]))
            kmeans = KMeans(n_clusters=k, random_state=42, n_init=10).fit(X)
            score = silhouette_score(X, kmeans.labels_)
            silhouettes.append(score)
            std = np.std(np.array(silhouettes))
            if verbose:
                print(f"Silhouette iteration {k} = {score:.3f}")
            if len(silhouettes) >= window:
                std = np.std(silhouettes[-window:])
                if std < tolerance:
                    print(f"Converged at k={k} (std={std:.4f})")
                    break
        # pick the k that gave the max silhouette
        best_index = np.argmax(silhouettes)
        n_clusters = k_values[best_index]  # <-- use k_values, not X
        if verbose:
            print("## Optimal number of clusters:", n_clusters)

    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=n_clusters)
    cluster_labels = kmeans.fit_predict(X)

    clusters = {node_id: int(label)
                for node_id, label in zip(node_ids, cluster_labels)}
    return clusters


def assign_coordinates(graph, clusters):
    """
    Creates positions for NetworkX nodes such that nodes in the same cluster
    are closer together.
    """
    # place clusters on a circle, nodes in cluster randomly around center
    cluster_centers = {}
    n_clusters = len(set(clusters.values()))
    angle_step = 2 * np.pi / n_clusters

    for i, cluster_id in enumerate(sorted(set(clusters.values()))):
        cluster_centers[cluster_id] = np.array(
            [np.cos(i * angle_step), np.sin(i * angle_step)]
        )

    pos = {}
    for node in graph.nodes:
        center = cluster_centers[clusters[node]]
        # small random offset within cluster
        offset = np.random.normal(scale=0.1, size=2)
        pos[node] = center + offset
    return pos


def complete_cluster(node_list, cluster_dict, cluster_idx):
    """
    Function to assign a cluster index for unassigned nodes in a dictionary
    """
    unassigned = set(node_list).difference(set(cluster_dict.keys()))
    new_assignments = [(nd, cluster_idx) for nd in unassigned]
    cluster_dict.update(dict(new_assignments))
    return cluster_dict


def build_dashboard(
    G,
    compounds,
    title,
    outfile,
    size=(1400, 800),
    layout_function="kamada_kawai",
    map_field="energy",
    verbose=True,
    **kwargs,
):
    """
    Wrapper function to generate HTML visualizations for a given network.

    Input:
    - G (nx.Graph): object as generated from RXReader. For profile support,
      it should contain a graph["pathList"] property.
    - title (str): title for the visualization.
    - outfile (str): name of the output HTML file.
    - size (tuple): tuple of integers, size of the visualization in pixels.
    - layout_function (nx.object, optional): Function to generate graph layout.
    - map_field (str): name of the field used for node coloring.

    Output:
    - lay (bokey.obj): Bokeh layout as generated by full_view_layout()
    """
    try:
        assert len(G.edges) > 0
    except AssertionError:
        print(
            "## WARNING! Chemical reaction network has no reactions. Check "
            "whether model variables (e.g., electronic method, solvent etc) "
            "fit model data in the MongoDB. Aborting html creation."
        )
        return None

    if verbose:
        print("## Writing {f1} output file".format(f1=outfile))
    # Define sizing
    w1 = int(size[0] * 4 / 7)
    w2 = int(size[0] * 3 / 7)
    wu = int(size[0] / 7)
    h = int(size[1] * 6 / 8)

    sizing_dict = {"w1": w1, "w2": w2, "wu": wu, "h": h}

    # Define custom classes

    style_template = """
    {% block postamble %}
	<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/dgarayr/jsmol_to_bokeh/jsmol_to_bokeh.min.js"></script>
    <style>
    .bk-root .bk-btn-default {
        font-size: 1.2vh;
    }
    .bk-root .bk-input {
        font-size: 1.2vh;
        padding-bottom: 5px;
        padding-top: 5px;
    }
    .bk-root .bk {
        font-size: 1.2vh;
    }
    .bk-root .bk-clearfix{
        padding-bottom: 0.8vh;
    }
    </style>
    {% endblock %}
    """
    if layout_function == "KMeans":  # custom clustering of nodes
        # this should be modifiable later
        cluster_property = "xyzdes"
        descriptors, prop_values = {}, []
        for nd in G.nodes(data=True):
            prop = nd[1][cluster_property]
            prop_values.append(prop)
        # prop_values,flag = aggregate_property(G,cluster_property)#,"none")
        # print("propvalues", prop_values)
        descriptors = dict(zip(G.nodes(), prop_values))
        clusters = cluster_nodes(descriptors)  # , n_clusters=5)
        posx = assign_coordinates(G, clusters)
    else:
        layout_function = getattr(nx, f"{layout_function}_layout")
        posx = layout_function(G)

    # Add model field to all nodes and edges & also vibrations
    arxviz.add_models(G)

    # Other properties
    node_size = kwargs.get("node_size", 30)

    # Bokeh-powered visualization via RXVisualizer
    bk_fig, bk_graph = arxviz.bokeh_network_view(
        G,
        positions=posx,
        graph_title=title,
        width=w1,
        height=h,
        map_field=map_field,
        hide_energy=True,
        palette=kwargs["palette"],
        qual_mapping=kwargs.get("qual_mapping", {}),
    )
    bk_graph.node_renderer.glyph.size = node_size

    # bk_graph.selection_policy = bkm.NodesAndLinkedEdges()
    bk_graph.selection_policy = bkm.EdgesAndLinkedNodes()

    # Modify the hovering tools here to add additional fields, removing the previous ones first
    valid_tools = [tool for tool in bk_fig.tools if tool.description]
    old_hovers = [tool for tool in valid_tools if "hover" in tool.description]
    for tool in old_hovers:
        bk_fig.tools.remove(tool)

    # custom edge hovering to reduce noise
    #
    hover_edgeJS = """
    var erend = graph.edge_renderer.data_source
    var label1 = String.fromCharCode(916).concat("E1")
    var label2 = String.fromCharCode(916).concat("E2")
    if (cb_data.index.indices.length > 0) {
        var ndx = cb_data.index.indices[0]
        var tsname = erend.data["name"][ndx]
        if (tsname.includes('TSb')){
            hover.tooltips = [["tag","@name"]]
        } else {
            hover.tooltips = [["tag","@name"],["charge","@chargeStr"],
                                ["multiplicity","@multiplicityStr"],["formula","@formulaStr"],
                                [label1,"@deltaE1"],[label2,"@deltaE2"]]
        }
    }
    """

    hide_barrlessJS = """
        var erend = graph.edge_renderer.data_source
        var nrend = graph.node_renderer.data_source
        var edgenames = erend.data["name"]
        var nodenames = nrend.data["name"]
        var numEdges = edgenames.length
        var numNodes = nodenames.length
        var statusCounter = counter[0]
        var connectedNodes = []
        var labsNodes = figure.center[2].source.data
        
    
        if (statusCounter == 0){
        // remove and set 1
            for (let j = 0; j < numEdges; j++){
                var is_tsb = edgenames[j].includes("TSb")
                if (is_tsb) {
                    erend.data["start"][j] = null            
                    erend.data["end"][j] = null            
                }
                else {
                    connectedNodes.push(erend.data["start"][j])
                    connectedNodes.push(erend.data["end"][j])
                }
            }
            for (let i = 0; i < numNodes; i++){
                var nname = nodenames[i]
                if (!connectedNodes.includes(nname)) {
                    nrend.data["index"][i] = null
                    labsNodes["nnames"][i] = " "
                }
            }
            statusCounter = 1
        } else {
        // restore and set counter back to zero
             for (let j = 0; j < numEdges; j++){
                var is_tsb = edgenames[j].includes("TSb")
                if (is_tsb){
                    erend.data["start"][j] = backupEdgeRoutes["start"][j]            
                    erend.data["end"][j] = backupEdgeRoutes["end"][j]
                }
            }
            for (let i = 0; i < numNodes; i++) {
                if (nrend.data["index"][i] == null){
                    nrend.data["index"][i] = backupNodes["index"][i]
                    labsNodes["nnames"][i] = backupNodes["name"][i]
                }
            }
            statusCounter = 0
        }
        counter[0] = statusCounter
        nrend.change.emit()
        erend.change.emit()
        """

    # Custom locateMolecule function to support search by SMILES
    locateMolecule = """
		// source - source object for JSMol
		// pass graph and fetch node and edge renderers
		// from fig, we modify x_range and y_range. Default plot starts from -1.2 to 1.2,
		var nrend = graph.node_renderer.data_source
		var erend = graph.edge_renderer.data_source
		var layout = graph.layout_provider.graph_layout
		// fetch the query in the data sources, choosing the appropiate renderer depending on the query
		var mol_query = text_input.value
		if (mol_query.includes("TS") || mol_query.includes("ts")) {
			var renderer = erend
			var other_renderer = nrend
            var pool_smiles = []
            var pool_inchikeys = []
        } else {
			var renderer = nrend
			var other_renderer = erend
            var pool_smiles = renderer.data["smilesStr"]
            var pool_inchikeys = renderer.data["inchikey"]
		}
		var pool_names = renderer.data["name"]

		// split species joined by + sign, smiles by //, inchikeys are already listd
        var pool_species = pool_names.map((name) => name.split("+"))
        var pool_smiles_split = pool_smiles.map((smi) => smi.split("//"))
        
        var split_ikey = function(ikey){
            var terms = [ikey.slice(0,14),ikey.slice(15,25),ikey];
            return terms}
        var pool_inchikeys_split = pool_inchikeys.map((ikeys) => ikeys.map(split_ikey).flat())

		// function to match results in the array
		var getSubstringIndices = function(arr,query){
			return arr.reduce(
					function(matches,tgt,i){
							if (tgt.includes(query))
						{matches.push(i)};
							return matches;
					},
					[]);
		}

        if (mol_query.includes("+")) {
			var ndx_u1 = pool_names.indexOf(mol_query)
			if (ndx_u1 < 0) {var ndx1 = []} 
            else {var ndx1 = [ndx_u1]}
        } else {
			var ndx1 = getSubstringIndices(pool_species,mol_query) 
        }

        var ndx2 = getSubstringIndices(pool_smiles_split,mol_query)
        var ndx3 = getSubstringIndices(pool_inchikeys_split,mol_query)
        
        // check all -> only choose the ones having matches => if several do, order of preference is ikey/smiles/name

        if (ndx3.length > 0){
            var ndx = ndx3
        } else if (ndx2.length > 0) {
            var ndx = ndx2
        } else if (ndx1.length > 0) {
            var ndx = ndx1
        } else {
            var ndx = []
        }

		// locate positions of the node or of the nodes defining an edge
		if (mol_query.includes("TS") || mol_query.includes("ts")) {
			var n1 = renderer.data["start"][ndx]
			var n2 = renderer.data["end"][ndx]
			var pos1 = layout[n1]
			var pos2 = layout[n2]
			var positions = new Array(2)
			positions[0] = 0.5*(pos1[0]+pos2[0])
			positions[1] = 0.5*(pos1[1]+pos2[1])
		} else {
			var positions = layout[pool_names[ndx[0]]]
		}
		if (ndx.length > 0) {
			// clearing other sel. avoids problems for model loading sometimes
			other_renderer.selected.indices = []
			renderer.selected.indices = ndx
			fig.x_range.start = positions[0] - 0.5
			fig.x_range.end = positions[0] + 0.5
			fig.y_range.start = positions[1] - 0.5
			fig.y_range.end = positions[1] + 0.5
		}
		"""

    # Callback for exporting the currently viewed nodes
    exportCurrent = """
    	var nrend = graph.node_renderer.data_source
        var nodeIndices = nrend.data["index"]
        var presentNodes = nodeIndices.filter((node) => node != null)
        var outDict = {nodes: presentNodes}
        
        // downloading a file
        function download(content, fileName, contentType) {
            var a = document.createElement("a")
            var file = new Blob([content], {type: contentType})
            a.href = URL.createObjectURL(file)
            a.download = fileName
            a.click()
        }
        download(JSON.stringify(outDict),"vizchemoton_export_sel.json","text/plain")

    """

    tooltips = [
        ("tag", "@name"),
        ("charge", "@chargeStr"),
        ("multiplicity", "@multiplicityStr"),
        ("formula", "@formulaStr"),
        ("smiles", "@smilesStr"),
    ]
    tooltips += kwargs.get("custom_hovers", [])

    hover_node = bkm.HoverTool(
        description="Node hover",
        renderers=[bk_graph.node_renderer],
        tooltips=tooltips,
        formatters={"@energy": "printf"},
    )
    bk_fig.add_tools(hover_node)
    hover_edge = bkm.HoverTool(
        description="Edge hover",
        renderers=[bk_graph.edge_renderer],
        formatters={"@energy": "printf"},
        line_policy="interp",
    )
    hover_edge.callback = bkm.CustomJS(
        args={"hover": hover_edge, "graph": bk_graph}, code=hover_edgeJS
    )
    bk_fig.add_tools(hover_edge)

    highl_callback = bkm.CustomJS(args={"graph": bk_graph},
            code=arxviz.js_callback_dict["highlightNeighbors"]
    )

    # We need edge backups
    edgesource = bk_graph.edge_renderer.data_source
    backup_edges = {
        "start": copy.deepcopy(edgesource.data["start"]),
        "end": copy.deepcopy(edgesource.data["end"]),
    }
    backup_nodes = {
        "index": bk_graph.node_renderer.data_source.data["index"],
        "name": bk_graph.node_renderer.data_source.data["name"],
    }
    hide_barrless_callback = bkm.CustomJS(
        args={
            "graph": bk_graph,
            "figure": bk_fig,
            "counter": [0],
            "backupNodes": backup_nodes,
            "backupEdgeRoutes": backup_edges,
        },
        code=hide_barrlessJS,
    )

    lay = arxviz.full_view_layout(bk_fig, bk_graph, sizing_dict=sizing_dict)

    # add a button to the layout
    b_highlight = bkm.Button(
        label="Highlight neighbors", max_width=int(w1 / 6), align="center"
    )
    b_highlight.js_on_click(highl_callback)
    b_hidebarrless = bkm.Button(
        label="Hide barrierless", max_width=int(w1 / 6), align="center"
    )
    b_hidebarrless.js_on_click(hide_barrless_callback)

    sel_row = lay.children[0][0].children[2]
    sel_row.children[1].max_width = int(w1 / 6)
    sel_row.children = (sel_row.children[0:2] + [b_highlight, b_hidebarrless]
                        + [sel_row.children[-1]]
    )

    # Export functionality
    export_callback = bkm.CustomJS(
        args={"figure": bk_fig, "graph": bk_graph}, code=exportCurrent
    )
    # Additional upper button -> readjust spacing to fit
    up_row = lay.children[0][0].children[0]
    b_export = bkm.Button(
        label="Export current nodes", max_width=int(w1 / 6), align="center"
    )
    b_export.js_on_click(export_callback)

    for item in up_row.children:
        item.max_width = int(w1 / 6)

    up_row.children.append(b_export)

    # Modify the callback of the locate molecule button
    text_input = sel_row.children[0]
    js_mol_locator_nw = bkm.CustomJS(
        args={"graph": bk_graph, "fig": bk_fig, "text_input": text_input},
        code=locateMolecule,
    )
    sel_button = sel_row.children[1]
    sel_button.js_event_callbacks["button_click"] = [js_mol_locator_nw]
    sel_button.js_on_click(js_mol_locator_nw)

    bokeh.plotting.output_file(outfile, title=title, mode="cdn")
    bokeh.plotting.save(lay, template=style_template)

    return lay, bk_fig, bk_graph


def scale_xyz_list(xyz, displ_vector=np.zeros(3)):
    """
    Bohr-to-angstrom scaling of a list of XYZ coordinates of the form
    [atom, [x, y, z]].

    Input:
    - xyz (list): XYZ coordinates, containing a list [atom, [x,y,z]] with
    atom being a string and x,y,z floats.
    - displ_vector (np.Array, optional): for translating the geometry.

    Output:
    - xyz_nw (list): scaled XYZ coordinates in the same format as the input.
    """

    bohr_to_ang = 0.529
    xyz_arr = np.array([item[1] for item in xyz]) * bohr_to_ang + displ_vector
    xyz_nw = [[item[0], list(xyz_arr[ii])] for ii, item in enumerate(xyz)]
    return xyz_nw


def xyz_list_to_xyz_block(xyz):
    """
    Transform a list of xyz coordinates [atom, [x, y, z]] into a string block.

    Input:
    - xyz (list): XYZ coordinates, containing a list [atom, [x,y,z]] with
    atom being a string and x,y,z floats.

    Output:
    - xyz_block (str): newline-joined block of the form
    a1,x1,y1,z2\na2,x2,y2,z2...
    """

    xyz_block = "\n".join(["%s %.6f %.6f %.6f" % (item[0], *item[1])
                                                  for item in xyz])
    return xyz_block


def formula_from_xyz_block(xyz):
    """
    Generates the molecular formula for a given XYZ geometry.

    Input:
    - xyz (list): XYZ coordinates, containing a list [atom, [x,y,z]] with
    atom being a string and x,y,z floats.

    Output:
    - formula (str): molecular formula from the input geometry.
    """
    labels = [item[0] for item in xyz]
    counter_list = sorted(Counter(labels).items())
    formula = ""
    for atom, ct in counter_list:
        if ct == 1:
            formula += atom
        else:
            formula += "%s%d" % (atom, ct)
    return formula


def sort_edge_names(edge_tuple):
    """
    Helper function to sort edge tuples lexicographically.

    Input:
    - edge_tuple (tuple): edge specification as a pair of node names.

    Output:
    - lexico_tuple (tuple): lexicographically sorted tuple.
    """
    n1, n2 = [int(nd) for nd in edge_tuple]
    srt_pair = sorted([n1, n2])
    lexico_tuple = tuple((str(nd) for nd in srt_pair))
    return lexico_tuple


def preprocess_compounds(compounds):
    """
    Helper function to process compounds properties.
    """
    tgt_vars = ["energy", "charge", "multiplicity"]
    for comp in compounds.values():
        for vv in tgt_vars:
            if not isinstance(comp[vv], list):
                comp[vv] = [comp[vv]]


def build_graph_edges(reaction_list):
    """
    Build graph edges.
    """
    return [(it[0], it[1], {"tsidx": it[2]}) for it in reaction_list[1:]]


def get_node_name_and_geometry(comp, dist_adduct, bohr_to_ang):
    """
    Helper function to retrieve the node name and geometry.
    """
    if isinstance(comp["crn_id"], list):
        comp["crn_id"] = "+".join(comp["crn_id"])
    if "+" in comp["crn_id"]:  # or isinstance(comp["crn_id"], list):
        # node_name = "+".join(comp["crn_id"])
        node_name = comp["crn_id"]
        xyz_list = comp["xyz"]
        xyz0_arr = np.array([item[1] for item in xyz_list[0]]) * bohr_to_ang
        cntr = xyz0_arr.mean(axis=0)
        xyz0 = [[item[0], list(xyz0_arr[ii])]
                 for ii, item in enumerate(xyz_list[0])]
        xyz_full = xyz0

        for ii, xyz in enumerate(xyz_list[1:]):
            displ_vec = cntr + (ii + 1) * dist_adduct
            xyz_arr = np.array([it[1] for it in xyz]) * bohr_to_ang + displ_vec
            xyz_nw = [[item[0], list(xyz_arr[ii])]
                      for ii, item in enumerate(xyz)]
            xyz_full += xyz_nw
    else:
        node_name = comp["crn_id"]
        xyz_list = [comp["xyz"]]
        xyz_arr = np.array([item[1] for item in xyz_list[0]]) * bohr_to_ang
        xyz_full = [[item[0], list(xyz_arr[ii])]
                     for ii, item in enumerate(xyz_list[0])]

    return node_name, xyz_full, xyz_list


def add_node_attributes(graph, compounds, node_renaming, dist_adduct,
                        bohr_to_ang):
    """
    Add nodes attributes to the graph for building the HTML file.
    """
    for nd in graph.nodes(data=True):
        comp = compounds[nd[0]]
        tmp = get_node_name_and_geometry(comp, dist_adduct, bohr_to_ang)
        node_name, xyz_full, xyz_list = tmp
        node_renaming[nd[0]] = node_name
        strtmp = "%s %.6f %.6f %.6f"
        _xyz = "\n".join([strtmp % (item[0], *item[1]) for item in xyz_full])
        nd[1]["geometry"] = _xyz
        nd[1]["energy"] = sum(comp["energy"])
        nd[1]["ZPVE"] = 0.0
        nd[1]["name"] = node_name
        nd[1]["degree"] = graph.degree(nd[0])
        nd[1]["charge"] = comp["charge"]
        nd[1]["multiplicity"] = comp["multiplicity"]
        nd[1]["formula"] = [formula_from_xyz_block(xyz) for xyz in xyz_list]
        nd[1]["neighbors"] = list(graph.neighbors(nd[0]))
        nd[1]["smiles"] = str(comp.get("smiles", "None")).split("//")
        nd[1]["inchikey"] = str(comp.get("inchikey", "None")).split("//")
        nd[1]["xyzdes"] = comp["xyzdes"]


def add_edge_attributes(graph, compounds):
    """
    Add edges attributes to the graph for building the HTML file.
    """
    compounds_renamed = {}
    for _, comp in compounds.items():
        if isinstance(comp["crn_id"], list):
            new_key = "+".join(comp["crn_id"])
            compounds_renamed[new_key] = comp
        else:
            compounds_renamed[comp["crn_id"]] = comp
    for ii, ed in enumerate(graph.edges(data=True)):
        e1, e2 = [sum(compounds_renamed[nd]["energy"]) for nd in ed[0:2]]
        if ed[2]["tsidx"] == None or ed[2]["tsidx"] == "None":
            e_ts = max(e1, e2)
            ed[2]["name"] = "TSb_%04d" % ii
            ed[2]["geometry"] = None
            ed[2]["energy"] = 0.0
            ed[2]["ZPVE"] = 0.0
            delta_e1 = (e_ts - e1, ed[0])
            delta_e2 = (e_ts - e2, ed[1])
            ed[2]["deltaE1"] = "%.2f (%s)" % delta_e1
            ed[2]["deltaE2"] = "%.2f (%s)" % delta_e2
            continue
        ts_compound = compounds[ed[2]["tsidx"]]
        xyz_list = [ts_compound["xyz"]]
        geom = scale_xyz_list(xyz_list[0])
        ed[2]["geometry"] = xyz_list_to_xyz_block(geom)
        ed[2]["name"] = ts_compound["crn_id"]
        e_ts = sum(ts_compound["energy"])
        delta_e1 = (e_ts - e1, ed[0])
        delta_e2 = (e_ts - e2, ed[1])
        ed[2]["deltaE1"] = "%.2f (%s)" % delta_e1
        ed[2]["deltaE2"] = "%.2f (%s)" % delta_e2
        ed[2]["energy"] = e_ts
        ed[2]["ZPVE"] = 0.0
        ed[2]["charge"] = ts_compound["charge"]
        ed[2]["multiplicity"] = ts_compound["multiplicity"]
        ed[2]["formula"] = [formula_from_xyz_block(xyz) for xyz in xyz_list]


def format_string_attributes(graph):
    """
    Processes node & edge attributes that are shown as strings in the
    final dashboard
    """
    node_attrs = ["charge", "multiplicity", "formula", "smiles"]
    edge_attrs = ["charge", "multiplicity", "formula"]
    for nd in graph.nodes(data=True):
        for tgt in node_attrs:
            nd[1][tgt + "Str"] = "//".join([str(item) for item in nd[1][tgt]])

    for ed in graph.edges(data=True):
        for tgt in edge_attrs:
            if tgt not in ed[2].keys():
                continue
            ed[2][tgt + "Str"] = "//".join([str(item) for item in ed[2][tgt]])

    return None


def _clean_empty_entries(compounds):
    """
    Preprocessing function to remove empty dictionaries in compounds object.
    """
    filtered_compounds = {}
    for c in compounds:
        if compounds[c] != {}:
            filtered_compounds[c] = compounds[c]
    return filtered_compounds


def process_graph(reaction_list, compounds, dist_adduct=3.0):
    """
    Wrapper function to generate a nx.Graph from a list of reactions and a
    dictionary of compounds, including XYZ-formatted geometries where
    individual geometries of the species forming adducts are joined.
    """
    compounds = _clean_empty_entries(compounds)
    bohr_to_ang = 0.529177
    graph = nx.Graph()
    edge_list = build_graph_edges(reaction_list)
    graph.add_edges_from(edge_list)
    node_renaming = {}
    preprocess_compounds(compounds)
    add_node_attributes(graph, compounds, node_renaming, dist_adduct,
                        bohr_to_ang)
    nx.relabel_nodes(graph, node_renaming, copy=False)

    # update neighbors after renaming
    for nd in graph.nodes(data=True):
        nd[1]["neighbors"] = list(graph.neighbors(nd[0]))

    add_edge_attributes(graph, compounds)
    format_string_attributes(graph)

    return graph


def format_value_list(val_list, fmt="%.4f", sep="//"):
    """
    TO-DO
    """
    fvlist = [fmt % vv if vv is not None else "None" for vv in val_list]
    return sep.join(fvlist)


def aggregate_property(Gx, prop_name, agg_func="mean", na_value=0):
    """
    TO-DO
    """
    fmap = {
        "max": np.max,
        "min": np.min,
        "mean": np.mean,
        "sum": np.sum,
        "none": lambda x: x,
    }
    func = fmap.get(agg_func, np.mean)
    agg_values = []
    flags = []
    for nd in Gx.nodes(data=True):
        prop = nd[1][prop_name]
        print("PROP", prop_name, prop)
        flag = 0
        if isinstance(prop, float) or isinstance(prop, int):
            val = prop
        elif isinstance(prop, list):
            values = [item if item is not None else np.nan
                      for item in nd[1][prop_name]]
            mask = np.isnan(values)
            values = np.where(mask, na_value, values)
            if np.all(mask):
                flag = 2
            elif np.any(mask):
                flag = 1
            val = func(values)
        elif prop is None:
            val = na_value
            flag = 2

        agg_values.append(val)
        flags.append(flag)
    return agg_values, flags
